import 'package:digi/screens/home_screen.dart';
import 'package:flutter/material.dart';
//calling Firebase.initializeApp from the firebase_core package with the configuration from your new firebase_options.dart file
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this file exists and is generated by FlutterFire CLI
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:nfc_manager/nfc_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Awesome Notifications
  AwesomeNotifications().initialize(
    null, // icon for notification, null uses default app icon
    [
      NotificationChannel(
        channelKey: 'basic_channel',
        channelName: 'Basic Notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: const Color(0xFF9D50DD),
        importance: NotificationImportance.High,
        channelShowBadge: true,
      ),
    ],
    debug: true,
  );

  // Request notification permissions
  await AwesomeNotifications().requestPermissionToSendNotifications();

  // Check NFC availability
  bool isNfcAvailable = await NfcManager.instance.isAvailable();
  print("NFC Available: $isNfcAvailable");

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
            seedColor: const Color.fromARGB(255, 175, 153, 214)),
        useMaterial3: true,
      ),
      home: HomeScreen(),
    );
  }
}
