name: digi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_database: ^11.0.0
  awesome_notifications: ^0.10.1
  lottie: ^3.1.2
  url_launcher: ^6.1.14
  nfc_manager: ^3.4.0
  ndef: ^0.3.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/money-bag.png"
  adaptive_icon_background: "#FFFFFFFF" # Specify a background color
  adaptive_icon_foreground: "assets/icons/d.png"
